import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";

const fontStyle = Barlow({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontStyle.className} bg-zinc-950 text-primary-foreground antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
