import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ReduxProvider } from "@/providers/reduxProvider";
import Navbar from "@/components/layout/navigation/Navbar";

const fontStyle = Barlow({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark">
        <body className={`${fontStyle.className} antialiased`}>
          <ReduxProvider>
            <Navbar />
            {children}
          </ReduxProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
